### ISSUE TITLE
Considering forking this to add falcon-swagger

### ISSUE THREAD

**Issue by advance512** [ampedandwired/bottle-swagger#5]
Would this be okay?

Or would you rather merge the two and generate based on a flag?

**Comment by ampedandwired** [comment]
Is [this](https://github.com/dutradda/falcon-swagger) the project that you mean? After having a quick look, I can't see how bottle-swagger would fit in with it - it seems to have it's own swagger support built it?

Anyway, I'm not too familiar with Falcon, but it feels like it should probably be a separate project from this one.

**Comment by advance512** [comment]
Okay, closing.
